# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - innovationchallenge

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  AZURE_WEBAPP_NAME: basejunk2207
  AZURE_WEBAPP_PACKAGE_PATH: 'basejunk2207'
  NODE_VERSION: '14.20.00'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.20.0'

      - name: npm install, build, and test
        run: |
          npm --version 2>&1 log.log || true
          set NODE_TLS_REJECT_UNAUTHORIZED=0 2>&1 log.log || true
          npm config set strict-ssl false 2>&1 log.log || true
          npm config set registry http://registry.npmjs.org/ 2>&1 log.log || true
          npm config -g delete ca 2>&1 log.log || true
          yarn config
          npm install --legacy-peer-deps --force
          npm install
          npm run build --if-present
          npm run test --if-present
          npm start 2>&1 log.log || true
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          run: |
               echo '{ script: "serve", env: { PM2_SERVE_SPA: "true", PM2_SERVE_HOMEPAGE: "/index.html" } }' >> basejunk2207/process.json

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'innovationchallenge'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DB5D89E9E7F745FFA0AAAA7A49B0BFB3 }}
          package: basejunk2207
